Board meeting notes May 2021
InnerSourceCommons/innersourcecommons.org pull request #125
Opened 2021-05-26 17:05 UTC by lenucksi

2021-05-26 17:31 UTC, dicortazar requested changes

2021-05-26 17:31 UTC, dicortazar commented on content/about/board/2020-05-26.md
> +
Clare Dillon was present as well

2021-05-27 03:50 UTC, rrrutledge requested changes
Two name changes.

2021-05-27 03:50 UTC, rrrutledge commented on content/about/board/2020-05-26.md
> +* Russel Rutledge (Secretary)
```suggestion
* Russell Rutledge (Secretary)
```

2021-05-27 03:50 UTC, rrrutledge commented on content/about/board/2020-05-26.md
> +
```suggestion
Clare Dillon
```

2021-05-27 09:05 UTC, lenucksi commented on content/about/board/2020-05-26.md
> +
True indeed, thanks for pointing out!

2021-05-27 09:06 UTC, lenucksi commented
Addressed both change requests.

2021-05-28 12:39 UTC, MaineC commented on content/about/board/2020-05-26.md
> +* Isabell Drost-Fromm (President)
```suggestion
* Isabel Drost-Fromm (President)
```

2021-06-01 19:55 UTC, voborgus commented
What is the process of review?

2021-06-02 08:56 UTC, MaineC approved these changes

2021-06-04 16:05 UTC, dicortazar approved these changes

2021-06-07 10:22 UTC, MaineC commented
@lenucksi can this be merged?

2021-06-07 10:47 UTC, lenucksi commented
> @lenucksi can this be merged?

I see nothing against it. Didn't merge for @dicortazar's red review yet, although all changes have been addressed. Feel free to merge yourself too.

2021-06-07 11:16 UTC, merged