VIdeo links for events
InnerSourceCommons/innersourcecommons.org pull request #187
Opened 2021-10-24 21:16 UTC by spier

I noticed that when I am on the Event Overview page, I cannot find the recordings of previous Community Calls there. Instead all links bring me to the event page (eventbrite etc). To find the recording, I have to go to the youtube channel and search for it there, which is cumbersome.

This PR adds a  "Watch Recording" button, next to the "Open Event" button. 
That button will only be shown when the respective event has a `youtubeLink` property in the markdown file.

Besides adding the feature itself, I also added the links to the youtube videos for all Community Calls.
(video or playlist links for other events would have to be added separately)

_Note:_
The value of `youtubeLink` could be any URL. So we could use it to point to individual videos (for Community Calls), or to youtube playlists (for Summits).

## Things to do when reviewing the PR

- [ ] double check that I linked to the correct video links for the Community Calls
- [ ] the dark background of the "Watch Recording" isn't super pretty. any idea how to make that button look better?

2021-10-27 15:34 UTC, voborgus requested changes
I checked the links, everything is fine. Thanks a lot!

Left 1 comment.

2021-10-27 15:34 UTC, voborgus commented on layouts/events/list.html
> +              <a href="{{ .Params.youtubeLink }}"{{ with .Params.target }} target="{{ . }}"{{ end }} class="btn btn-secondary btn-sm">Watch Recording</a>
Since YouTube is the external site for us, I would propose to have all links to be opened in the new tab with target="_blank" field.

2021-10-28 08:10 UTC, spier commented
@voborgus as you suggested, all video links will be opened in a new page now.

Also added links to the remaining summits.

Please review again. If you are happy with it, please go ahead and merge this.

PS: Please note that my editor automatically removed some extra spaces in various files, making the review a bit harder. Sorry about that.

2021-10-28 09:43 UTC, voborgus approved these changes
Thanks a lot, let's move this to the site.

2021-10-28 09:43 UTC, merged