Terse notes for board meeting 2022-10-24
InnerSourceCommons/innersourcecommons.org pull request #390
Opened 2022-10-24 17:43 UTC by user-group

2022-10-24 17:54 UTC, spier requested changes
I adapted the formatting based on what I found in a [previous terse notes](https://raw.githubusercontent.com/InnerSourceCommons/innersourcecommons.org/master/content/about/board/2022-09-22.md).

Please review.

2022-10-24 17:54 UTC, spier commented on content/about/board/2022-10-24.md
> +
```suggestion
---
layout: page
show_meta: false
title: '2022-10-24'
---

```

Looks like you need this meta info at the beginning of the file to make it render correctly on the website.

2022-10-24 17:54 UTC, spier commented on content/about/board/2022-10-24.md
> +# Date and Time of Meeting
```suggestion
### Date and Time of Meeting

```

Changing headline to what I see in previous reports.
Also adding spacing.

2022-10-24 17:54 UTC, spier commented on content/about/board/2022-10-24.md
> +## Directors and Officers Present
```suggestion
### Roll call

#### Directors and Officers Present

```

Changing headline to what I see in previous reports.
Also adding spacing.

2022-10-24 17:54 UTC, spier commented on content/about/board/2022-10-24.md
> +## Directors and Officers Absent
```suggestion
#### Directors and Officers Absent

```

Changing headline to what I see in previous reports.
Also adding spacing.

2022-10-24 17:54 UTC, spier commented on content/about/board/2022-10-24.md
> +## Members Present
```suggestion
#### Members Present

```

Changing headline to what I see in previous reports.
Also adding spacing.

2022-10-24 17:54 UTC, spier commented on content/about/board/2022-10-24.md
> +# Votes Taken
```suggestion
### Votes Taken

```

Changing headline to what I see in previous reports.
Also adding spacing.

2022-10-24 17:54 UTC, tsadler1988 requested changes
Thanks @user-group! Just one commit suggestion re: timezones for next meeting.

2022-10-24 17:54 UTC, tsadler1988 commented on content/about/board/2022-10-24.md
> +* Next meeting 2022-11-28, 7 p.m-8 p.m. CEST / 12 p.m. - 1 p.m. CDT
```suggestion
* Next meeting 2022-11-28, 7 p.m-8 p.m. CET / 12 p.m. - 1 p.m. CST
```
Daylight savings will be over by this date.

2022-10-25 09:02 UTC, user-group reviewed
i can't seem to click 'approve', so I'm just leaving this comment here as not sure what to do.

2022-10-25 09:03 UTC, user-group reviewed
can only comment, can't seem to approve. not sure how to proceed (please help :-))

2022-10-25 09:55 UTC, rrrutledge commented
> can't seem to approve
Someone else has to approve.  You’re not allowed to approve your own PR :)

2022-10-25 15:15 UTC, lenucksi reviewed
Look fine, not sure with some of the role assignments though (i.e. chair and president, can someone take a second look in the vote register?)

2022-10-25 15:38 UTC, user-group commented
@lenucksi I assumed 'chair' was the meeting chair, but maybe that's not what I should have done? I think I copied all others from previous notes.

2022-10-26 11:45 UTC, maxcapraro reviewed
Thanks for writing such excellent terse notes, @user-group :-) I proposed one tiny change inline, other than this it's good to go from my side 🚀

2022-10-26 11:45 UTC, maxcapraro commented on content/about/board/2022-10-24.md
> +Maximiliano Capraro (Assistant Treasurer)
```suggestion
Maximilian Capraro (Assistant Treasurer)
```

I do like the sound of it, though :-)

2022-10-26 14:01 UTC, rrrutledge commented on content/about/board/2022-10-24.md
> +Maximiliano Capraro (Assistant Treasurer)
It does have a nice ring to it!

2022-11-06 23:27 UTC, tsadler1988 requested changes

2022-11-06 23:27 UTC, tsadler1988 commented on content/about/board/2022-10-24.md
> +Thomas Sadler (Chair)
```suggestion
Thomas Sadler (Secretary)
```

2022-11-06 23:27 UTC, tsadler1988 commented on content/about/board/2022-10-24.md
> +Danese Cooper (President)
```suggestion
Danese Cooper (Chair)
```

2022-11-06 23:28 UTC, tsadler1988 commented
> @lenucksi I assumed 'chair' was the meeting chair, but maybe that's not what I should have done? I think I copied all others from previous notes.

Yeah I think it's the individual's officer role rather than what they did in the meeting. I've made commit suggestions to fix this  :)

2022-11-07 16:41 UTC, tsadler1988 approved these changes

2022-11-07 16:42 UTC, tsadler1988 commented
@spier I think your suggestions have been incorporated, if you could approve this please?

2022-11-07 18:12 UTC, spier approved these changes

2022-11-10 18:41 UTC, lenucksi approved these changes
Looks fine to me. We still need 2-3 additional board members to sign off here. @MaineC @dicortazar @rrrutledge

2022-11-15 03:24 UTC, tsadler1988 commented
> Looks fine to me. We still need 2-3 additional board members to sign off here. @MaineC @dicortazar @rrrutledge

Previous terse notes haven't had more than 2 or 3 reviews so I think this is fine to merge.

2022-11-15 03:24 UTC, merged

2022-11-15 14:08 UTC, rrrutledge commented
> I think this is fine to merge

I agree!  These aren’t terribly complicated or controversial, so just getting them in makes sense.

2022-11-15 14:35 UTC, lenucksi commented
> > I think this is fine to merge
> 
> I agree! These aren’t terribly complicated or controversial, so just getting them in makes sense.

Good. Should we then add that to our meeting checklist?

2022-11-17 20:18 UTC, rrrutledge commented
In the [meeting checklist](https://github.com/InnerSourceCommons/foundation/blob/master/.github/ISSUE_TEMPLATE/board-meeting.md) it just says to merge in the week following the meeting.  Should we adjust somehow?

2022-11-18 16:29 UTC, lenucksi commented
> In the [meeting checklist](https://github.com/InnerSourceCommons/foundation/blob/master/.github/ISSUE_TEMPLATE/board-meeting.md) it just says to merge in the week following the meeting. Should we adjust somehow?

I think so. This differs from the practical/reality approach and thus we should update it with this. Make a PR invite the people, conclude & hopefully merge and have up-to-date material for the future.

2022-11-25 12:14 UTC, rrrutledge commented
I think that this PR was an exception since it was the first time that Klaas is working on it.  If you look at the months beforehand, these notes get an approval within a day or two of being opened.  The longest delays are getting the PR opened in the first place and then hitting the merge button after approval.

2022-11-25 12:23 UTC, lenucksi commented
> I think that this PR was an exception since it was the first time that Klaas is working on it. If you look at the months beforehand, these notes get an approval within a day or two of being opened. The longest delays are getting the PR opened in the first place and then hitting the merge button after approval.

I was more suggesting to add the 2 or 3 reviews suffice as @tsadler1988 pointed out here; https://github.com/InnerSourceCommons/innersourcecommons.org/pull/390#issuecomment-1314709510
What do you think about that?

2022-11-25 17:10 UTC, rrrutledge commented
Ah, makes sense!