i18n Foundation and adding Japanese pages
InnerSourceCommons/innersourcecommons.org pull request #425
Opened 2022-12-13 02:46 UTC by yuhattor

@voborgus @InnerSourceCommons/website-maintainers 
I have created a Japanese page on innersourcecommons.org, and there is a staging site at innersourcecommons.jp.
Please check and merge it:)

Now that we have this foundation in place, the next step may be to translate the materials into German, Russian, etc. I will create branches and make a base in the future to try it out after this PR is successfully merged.

There are still some issues with integration with Learning Path: all Learning Path materials now reside under content/en/, and they are moved correctly when gh-pages are created, so it doesn't essentially affect functionality. It's not pretty though, so I'll fix that in the future.

For more info, please check the issue #355

2022-12-13 07:37 UTC, yuhattor commented
Except for heroku slack inviter and some original broken pages, linkcheck has already succeeded. No Japanese-specific problems exist.

2022-12-13 08:56 UTC, voborgus requested changes
Million thanks for the huge work you're doing!

Some comments before the merge:

Looks like the last item in the menu still untranslated.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/9394918/207267271-503ab197-32dd-4424-a8cc-969ec3adda05.png">

Also noticed a bug (imho can leave for now but then to not to forget to do smth):
* Go to learning path.
* Change language to German (or other except `en` and `ja`).
* Go to home page. 

Language parameter continue to be German, but content is `rsynced` from English. If we change the language again, German option will be hidden. This was handled correctly previously when there are no pages was autogenerated from english but now we may consider another behaviour. I'm expect to live a long time without translation to all languages :)

2022-12-13 08:56 UTC, voborgus commented on content/ja/about/_index.md
> +        コミュニティ活動のほとんどは、<a href="https://innersourcecommons-inviter.herokuapp.com/">Slack</a> で行われています。また、メールの定期購読や、 <a href="https://twitter.com/InnerSourceOrg">Twitter</a>、 <a href="https://www.link
Since heroku inviter is going to disappear soon, suggest you to change the slack link to https://innersourcecommons.org/slack/

2022-12-13 08:56 UTC, voborgus commented on config/_default/menus.ru.yaml
> +  - name: Учиться
Обучение

2022-12-13 08:56 UTC, voborgus commented on config/_default/menus.ru.yaml
> +  - name: Путь обучения
Программа обучения

2022-12-13 08:56 UTC, voborgus commented on config/_default/menus.ru.yaml
> +  - name: Шаблоны
Паттерны

2022-12-13 08:56 UTC, voborgus commented on config/_default/menus.ru.yaml
> +  - name: Справочник услуг
Каталог услуг

2022-12-13 08:56 UTC, voborgus commented on config/_default/menus.ru.yaml
> +  - name: Члены
Участники

2022-12-13 08:56 UTC, voborgus commented on config/_default/menus.ru.yaml
> +  - name: Свяжитесь с нами
Контакты

2022-12-13 08:56 UTC, voborgus commented on config/_default/menus.ru.yaml
> +  - name: Учиться
Обучение

2022-12-13 08:56 UTC, voborgus commented on config/_default/menus.ru.yaml
> +  - name: Справочник услуг
Каталог услуг

2022-12-13 08:56 UTC, voborgus commented on config/_default/menus.ru.yaml
> +  - name: Члены
Участники

2022-12-13 08:56 UTC, voborgus commented on config/_default/menus.ru.yaml
> +  - name: Свяжитесь с нами
Контакты

2022-12-13 09:46 UTC, yuhattor commented
@voborgus 
This is a matter for debate. Actually, this move is done this way by design

It would be very stressful if, when viewing a German page, the user had to leave that locale every time they went to an untranslated page. The user would be taken unawares to an untranslated page, but if they were taken to a `/en` (Default) page, they would have to revert to their own language each time.

In many cases, for example in the case of Microsoft documentation, there are each types of pages available, even if they are not translated, as follows
https://azure.microsoft.com/ja-jp/updates/public-preview-v2-programming-model-for-azure-functions-using-python/
https://azure.microsoft.com/en-us/updates/public-preview-v2-programming-model-for-azure-functions-using-python/

So far, there are 27 markdown files under content/ja, since there are 100+ markdown files under content/en. And since rsync is supposed to skip files that exist, there is no need to translate all pages or even add them to the codebase.
Let's say someone wants to translate only a minimum of 10 .md files, including the top page, in a new language, he/she doesn't have to translate the whole thing.

wdyt?

2022-12-13 12:17 UTC, voborgus commented
You right, let's leave it for now – then we may decide other behaviour based on users feedback.

So small translation fixes left and ready to merge 👍🏻

2022-12-23 09:28 UTC, yuhattor commented
@voborgus Could you merge it now?!
I fixed the small menu mistranslation in Russian and all checks have passed:)

2022-12-23 09:28 UTC, yuhattor commented
Again, the staging page is live now
https://innersourcecommons.jp/ru/learn/learning-path/

2022-12-23 09:30 UTC, voborgus approved these changes
Thanks! Lets merge it

2022-12-23 09:30 UTC, merged

2022-12-23 09:33 UTC, yuhattor commented
Amazing!!!