Updates to the Board page for the 2023 Board
InnerSourceCommons/innersourcecommons.org pull request #531
Opened 2023-05-10 23:01 UTC by spier

2023-05-10 23:04 UTC, spier commented
@mcobby for this to go live I am only missing your profile picture and a brief bio of yourself. See [this](https://innersourcecommons.org/about/board/) for reference of what the others have written.

You can send this to me via Slack, and I can integrate it into this PR. Or you can contribute to this PR directly, whatever is faster for you.

cc @tsadler1988

2023-05-11 11:08 UTC, lenucksi commented on content/en/about/board/_index.md
> +Georg Grütter is a social coding evangelist and developer advocate at Bosch.IO. He co-founded and led the first InnerSource community at Bosch. Georg is a passionate software developer with over 30 y
That sentence was grammatically broken.

```suggestion
Georg Grütter is a social coding evangelist and developer advocate at Bosch.IO. He co-founded and led the first InnerSource community at Bosch. Georg is a passionate software developer with over 30 years of experience. Previously, he held various positions and roles at Bosch, Line Information, the Zurich System House, and DaimlerChrysler. Georg has created two open source projects, and also loves photography and chocolate.
```

2023-05-11 11:18 UTC, spier commented on content/en/about/board/_index.md
> +Georg Grütter is a social coding evangelist and developer advocate at Bosch.IO. He co-founded and led the first InnerSource community at Bosch. Georg is a passionate software developer with over 30 y
Thanks for the fix!

2023-05-15 14:40 UTC, rrrutledge requested changes
Only include current director roles.

2023-05-15 14:40 UTC, rrrutledge commented on content/en/about/board/_index.md
> +{{< board-member name="Danese Cooper" title="Chairperson" image="/images/about/Danese_Cooper.jpg" >}}
```suggestion
{{< board-member name="Danese Cooper" image="/images/about/Danese_Cooper.jpg" >}}
```

2023-05-15 19:08 UTC, spier commented
> Only include current director roles.

Great catch @rrrutledge, thank you!

2023-05-15 19:13 UTC, rrrutledge approved these changes
Thanks for updating, @spier ❗

2023-05-15 19:14 UTC, merged