[WIP] Brazilian Portuguese Language Support 🇧🇷
InnerSourceCommons/innersourcecommons.org pull request #553
Opened 2023-06-01 16:18 UTC by yuhattor

# Brazilian Portuguese Language Support

The InnerSource Commons (ISC) website is available in multiple languages. We appreciate your help in translating the site to make it accessible to Brazilian Portuguese speakers.

please keep in mind followings

Please note the following guidelines:

- Before beginning your translation, please read the i18n.md file for information on tools and processes.
- Do not edit or create any files under `content/en/learn/learning-path/`. These files are sourced from another repository and are not stored in the innersourcecommons.org repository. If you want to add or edit a language, please do so in the learning-path repository.
- Please do not include any untranslated files in your pull request (PR). Missing files will be automatically added from `content/en` at build time.

## Files to be translated

The following is a list of files that should be translated first. It is a good idea to translate from here, but you are not required to follow it.

**Setting files**

- [ ] i18n/pt-br.yaml
- [ ] config/_default/menus.pt-br.yaml

**Content files**

- [ ] content/pt-br/about/announcements/_index.md
- [ ] content/pt-br/about/_index.md
- [ ] content/pt-br/about/sponsors.md
- [ ] content/pt-br/about/members.md
- [ ] content/pt-br/about/board/_index.md
- [ ] content/pt-br/about/codeofconduct.md
- [ ] content/pt-br/about/contact.md
- [ ] content/pt-br/community/_index.md
- [ ] content/pt-br/community/services.md
- [ ] content/pt-br/events/_index.md
- [ ] content/pt-br/_index.md
- [ ] content/pt-br/learn/_index.md
- [ ] content/pt-br/learn/books/managing-innersource-projects.md
- [ ] content/pt-br/learn/books/innersource-patterns.md
- [ ] content/pt-br/learn/books/_index.md
- [ ] content/pt-br/learn/books/adopting-innersource-principles-and-case-studies.md
- [ ] content/pt-br/learn/books/understanding-the-innersource-checklist.md
- [ ] content/pt-br/learn/books/getting-started-with-innersource.md
- [ ] content/pt-br/learn/patterns.md
- [ ] content/pt-br/learn/research/state-of-innersource-survey-2021.md
- [ ] content/pt-br/learn/research/state-of-innersource-survey-2016.md
- [ ] content/pt-br/learn/research/_index.md
- [ ] content/pt-br/learn/research/state-of-innersource-survey-2020.md
- [ ] content/pt-br/redirects/patterns.md
- [ ] content/pt-br/stories/_index.md
- [ ] content/pt-br/stories/microsoft.md

### The conditions for merging are as follows

- [ ] Website-mainterners Approval
- [ ] Native check
	While machine translation can be useful for large volumes of text and can serve as a starting point for translation, it can also produce unprofessional results. In addition, since machine translation can be used by anyone with a browser extension, this translation project requires a more professional level
- [ ] At least 50% of the files in the "Files to be translated" section should be translated

2023-06-01 18:32 UTC, fer-correa requested changes
Please check the suggestions I've made so far.

I will resume the review asap

2023-06-01 18:32 UTC, fer-correa commented on content/pt-br/_index.md
> +        <p>Se você é novo no InnerSource ou quer saber mais sobre quem está implementando o InnerSource e por que e como começar, visite a seção de Aprendizado do site. Você encontrará uma variedade
Se você é novo no InnerSource ou deseja saber mais sobre quem está implementando  InnerSource e o porquê e como começar, visite a seção de aprendizado do site. Você encontrará diversos recursos para ajudar a acelerar sua jornada ao InnerSource, incluindo materiais de treinamento, práticas recomendadas, livros, gravações de eventos anteriores e estudos de caso.

2023-06-01 18:32 UTC, fer-correa commented on content/pt-br/_index.md
> +          <p>Apoiamos praticantes e aqueles que desejam aprender sobre o InnerSource por meio de uma ampla variedade de atividades. Para começar, junte-se à crescente comunidade ISC através do Slack
Apoiamos praticantes e aqueles que desejam aprender sobre InnerSource por meio de uma ampla variedade de atividades. Para começar, junte-se à crescente comunidade ISC através do Slack e se apresente. Você encontrará pessoas incríveis para lhe acompanhar em sua jornada InnerSource.

2023-06-01 18:32 UTC, fer-correa commented on content/pt-br/_index.md
> +        <p class="mb-4">A maior parte das ações na comunidade acontece em nosso <a href="https://join.slack.com/t/innersourcecommons/shared_invite/zt-1msf8vcqu-fYEHcyI1l4eSPq6rGprMXA">Canal do Slack<
<p class="mb-4">A maior parte das ações na comunidade acontece em nosso <a href="https://join.slack.com/t/innersourcecommons/shared_invite/zt-1msf8vcqu-fYEHcyI1l4eSPq6rGprMXA">Canal do Slack</a>. Você também pode se manter informado sobre as novidades, eventos e atividades da InnerSource Commons assinando nossa lista de e-mails abaixo, nos seguindo no <a href="https://twitter.com/InnerSourceOrg">Twitter</a> e no <a href="https://www.linkedin.com/company/innersourcecommons">LinkedIn</a>, e se inscrevendo em nosso <a href="https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA">Canal do YouTube</a>.</p>

2023-06-01 18:32 UTC, fer-correa commented on content/pt-br/about/_index.md
> +        <p>Nossa missão é estabelecer um corpo de conhecimento e educar indivíduos, organizações comerciais e sem fins lucrativos, centros de pesquisa e outras instituições sobre a adoção bem-sucedid
<p>Nossa missão é estabelecer uma base de conhecimento e educar indivíduos, organizações com e sem fins lucrativos, centros de pesquisa e outras instituições sobre a adoção bem-sucedida das melhores práticas de InnerSource.</p>

2023-06-01 18:32 UTC, fer-correa commented on content/pt-br/about/_index.md
> +        <p>Nós fornecemos um ambiente seguro para acumular e compartilhar conhecimento e experiências, encontrar melhores práticas, estabelecer padrões e ferramentas, produzir materiais educacionais
<p>Oferecemos um ambiente seguro para acumular e compartilhar conhecimentos e experiências, encontrar as melhores práticas, criar padrões e ferramentas, produzir materiais educacionais e promover pesquisas para avançar na compreensão, adoção e prática de InnerSource.

2023-06-01 18:32 UTC, fer-correa commented on content/pt-br/about/_index.md
> +          <p>A InnerSource Commons utiliza métodos de código aberto para fornecer às organizações que praticam InnerSource um fórum para discutir e aprimorar a prática do InnerSource por meio do comp
A InnerSource Commons utiliza métodos de Open Source para fornecer às organizações que praticam o InnerSource um fórum para discutir e melhorar a prática do InnerSource por meio do compartilhamento de experiências (sob a Regra de Chatham House), criação e revisão dos padrões de InnerSource e a troca aberta de ideias.

2023-06-01 18:32 UTC, fer-correa commented on content/pt-br/about/_index.md
> +        <p>Indivíduos e empresas interessados são bem-vindos a participar e contribuir com conteúdo para o ISC. Em geral, o conteúdo contribuído será disponibilizado sob a <a href="https://creativeco
<p>Indivíduos e empresas interessados ​​são bem-vindos a participar e contribuir com conteúdo para o ISC. Em geral, o conteúdo da contribuição será disponibilizado sob a licença <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International</a> atribuída a InnerSourceCommons.org. Nenhuma taxa é necessária para participar.</p>

2023-06-01 18:32 UTC, fer-correa commented on content/pt-br/about/_index.md
> +        <p>A comunidade InnerSource Commons é aberta a todos. Alguns participantes da comunidade vão além e podem ser convidados a se tornar membros do ISC. A InnerSource Commons é uma corporação de
<p>A comunidade InnerSource Commons é aberta a todas as pessoas. Alguns participantes da comunidade vão além, superando as expectativas, e podem ser convidados a se tornar membros do ISC. A InnerSource Commons é uma associação de membros, então os membros da ISC desempenham um papel semelhante aos acionistas de empresas de capital aberto.</p>

2023-06-01 18:32 UTC, fer-correa commented on content/pt-br/about/_index.md
> +        <p>Os membros têm direitos específicos no ISC; por exemplo, eles podem votar em eleições do conselho. Para ser elegível para a associação, a pessoa deve ser indicada por um membro atual. A as
<p>Os membros têm direitos específicos na ISC; por exemplo, eles podem votar em eleições do conselho. Para ser elegível como um membro, a pessoa deve ser indicada por um membro atual. A associação é baseada exclusivamente no mérito, sem custo algum e restrita a indivíduos.</p>

2023-06-01 18:32 UTC, fer-correa commented on content/pt-br/about/_index.md
> +          <p>A InnerSource Commons é uma organização sem fins lucrativos 501(c)(3) governada por um conjunto de estatutos corporativos. O Conselho de Diretores estabelece as políticas e nomeia os ofi
<p>A InnerSource Commons é uma organização sem fins lucrativos 501(c)(3) governada por um conjunto de estatutos corporativos. O Conselho de Administração define as políticas e nomeia os diretores responsáveis por estabelecer e executar essas políticas. O Conselho é eleito pelos membros da associação anualmente.</p>

2023-06-19 00:05 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +subtitle: A InnerSource Commons é uma organização sem fins lucrativos 501(c)(3) governada por um conjunto de estatutos sociais. O Conselho de Administração estabelece as políticas e nomeia os executi
subtitle: A InnerSource Commons é uma organização sem fins lucrativos 501(c)(3) regida por um conjunto de estatutos corporativos. O Conselho de Administração define a política e nomeia diretores que definem e executam a política. O Conselho é eleito pelos membros anualmente. A InnerSource Commons está incorporada nos Estados Unidos. À medida que a comunidade cresce, esperamos fundar organizações irmãs na União Europeia, América Latina e outras partes do mundo.

2023-06-19 00:10 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +Isabel Drost-Fromm é Estrategista de Código Aberto na Europace AG, na Alemanha. Ela é membro da Apache Software Foundation, co-fundadora do Apache Mahout e orientou vários projetos em fase de incubaç
Isabel Drost-Fromm é Estrategista de Open Source na Europace AG, na Alemanha. Ela é membro da Apache Software Foundation, co-fundadora do Apache Mahout e orientou vários projetos em fase de incubação. Isabel se interessa por tudo relacionado a FOSS, busca e mineração de texto, com um bom conhecimento em aprendizado de máquina. Seguindo a natureza das pessoas que vivem em Berlim, ela adora receber amigos para uma breve visita. Como resultado, ela co-fundou e ainda é uma das mentes criativas por trás do Berlin Buzzwords, uma conferência de tecnologia sobre busca, escalabilidade e armazenamento.

2023-06-19 00:13 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +Daniel Izquierdo Cortazar é pesquisador e um dos fundadores da Bitergia, uma empresa que oferece análises de software para ecossistemas de código aberto. Atualmente, é diretor de dados da Bitergia e
```suggestion
Daniel Izquierdo Cortazar é pesquisador e um dos fundadores da Bitergia, uma empresa que oferece análises de software para ecossistemas Open Source. Atualmente, é diretor de dados da Bitergia e concentra-se na qualidade dos dados, pesquisa de novas métricas, análises e estudos de interesse para os clientes da Bitergia por meio de mineração e processamento de dados. Daniel possui um doutorado em engenharia de open source software pela Universidad Rey Juan Carlos, em Madrid, onde se concentrou na análise de padrões de atividade de desenvolvedores com erros na comunidade Mozilla. Daniel faz parte do conselho e é membro da InnerSource Commons.
```

2023-06-19 00:15 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +Georg Grütter é um evangelista de código social e defensor de desenvolvedores na Bosch.IO. Ele co-fundou e liderou a primeira comunidade InnerSource na Bosch. Georg é um desenvolvedor de software apa
```suggestion
Georg Grütter é um evangelista de código social e defensor de desenvolvedores na Bosch.IO. Ele co-fundou e liderou a primeira comunidade InnerSource na Bosch. Georg é um desenvolvedor de software apaixonado com mais de 30 anos de experiência. Anteriormente, ocupou diversos cargos e funções na Bosch, Line Information, Zurich System House e DaimlerChrysler. Georg criou dois projetos open source e também adora fotografia e chocolate.
```

2023-06-19 00:18 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +Yuki é um especialista em tecnologia distinto, atualmente atuando como Arquiteto na GitHub, com vasta experiência em tecnologia em nuvem e metodologias DevOps. Ao longo de sua carreira, ele ofereceu
```suggestion
é um distinto especialista em tecnologia que atualmente atua como arquiteto no GitHub, com vasta experiência em tecnologia em nuvem e metodologias DevOps. Ao longo de sua carreira, ele ofereceu orientação valiosa e proficiência para uma infinidade de clientes corporativos, ajudando-os a aprimorar seus sistemas e processos. A área de especialização de Yuki é a transformação InnerSource e ele estabeleceu uma comunidade próspera no Japão que se envolveu com figuras proeminentes e líderes de pensamento da indústria. 
```

2023-06-19 00:18 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +ria. Como defensor apaixonado do InnerSource, Yuki traduziu uma vasta gama de materiais e organizou inúmeros workshops e apresentações em vídeo para disseminar a conscientização e a compreensão do as
```suggestion
Como defensor apaixonado do InnerSource, Yuki traduziu uma vasta gama de materiais e organizou inúmeros workshops e apresentações em vídeo para disseminar a conscientização e a compreensão do assunto. Ele se orgulha imensamente de servir como exemplo para outras regiões e continua comprometido em empregar sua experiência e conhecimento para beneficiar outros membros da comunidade.
```

2023-06-19 00:19 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +
```suggestion
```

2023-06-19 00:38 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +Silona Bonewald é Diretora Executiva do IEEE SA OPEN, uma plataforma abrangente que oferece à comunidade de código aberto opções econômicas para desenvolver e validar seus projetos. Anteriormente, el
```suggestion
Silona Bonewald é Diretora Executiva do IEEE SA OPEN, uma plataforma abrangente que oferece à comunidade Open Source opções econômicas para desenvolver e validar seus projetos. Anteriormente, ela foi vice-presidente de arquitetura de comunidade na Hyperledger, um esforço colaborativo global de código aberto sediado na Linux Foundation, onde integrou líderes financeiros, bancários, de IoT, cadeias de suprimentos e manufatura. Outras realizações profissionais notáveis incluem pioneirismo no processo InnerSource enquanto estava no PayPal, criação de um site de comércio eletrônico inovador e compatível com Six Sigma para a Siemens AG, e criação de uma arquitetura de sistema de gerenciamento de conteúdo (CMS) internacional para a Ubisoft.
```

2023-06-19 00:39 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +Maximilian Capraro é pesquisador e candidato a doutorado no Open Source Research Group na Friedrich-Alexander-University Erlangen-Nürnberg. Ele trabalhou em projetos de pesquisa de InnerSource com di
```suggestion
Maximilian Capraro é pesquisador e candidato a doutorado no Open Source Research Group na Friedrich-Alexander-University Erlangen-Nürnberg. Ele trabalhou em projetos de pesquisa de InnerSource com diversas empresas, incluindo Black Duck Software, Continental e várias unidades de negócios da Siemens. Ele desenvolveu o método de medição de fluxo de patch (para medir a colaboração no desenvolvimento de software) e o primeiro framework de classificação para projetos e programas InnerSource. Suas áreas de pesquisa incluem quantificação da colaboração no desenvolvimento de software, governança de InnerSource, incluindo aspectos legais e tributários, e muitos outros tópicos relacionados a InnerSource, Open Source e engenharia de software.
```

2023-06-19 00:45 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +Danese Cooper é a fundadora da InnerSource Commons. Ela é uma defensora de longa data do código aberto, tendo atuado anteriormente como chefe de software de código aberto do PayPal, CTO da Wikimedia
```suggestion
Danese Cooper é a fundadora da InnerSource Commons. Ela é uma Open Source advocate de longa data, tendo atuado anteriormente como Head de open source software do PayPal, CTO da Wikimedia Foundation, evangelista-chefe de open surce da Sun e diretora sênior de estratégias de open source da Intel. Danese também foi a primeira presidente da Node.js Foundation. Ela se concentra em criar comunidades open source saudáveis e já integrou os conselhos da Drupal Association, da Open Source Initiative e da Open Source Hardware Association. Ela também é consultora da Mozilla e da Apache Software Foundation. Danese também dirige uma bem-sucedida consultoria de open source que conta com clientes como a Fundação Bill & Melinda Gates, o SETI Institute, a Harris e a Numenta. Ela é conhecida por tricotar durante as reuniões.
```

2023-06-19 00:47 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +Johannes é co-criador do InnerSource Commons Learning Path e trabalhou na introdução do InnerSource na HERE Technologies, uma empresa líder em mapas digitais e localização. Atualmente, ele oferece co
```suggestion
Johannes é co-criador do InnerSource Commons Learning Path e trabalhou na introdução do InnerSource na HERE Technologies, uma empresa líder em mapas digitais e localização. Atualmente, ele oferece coaching e consultoria em Produtividade de Engenharia, Estratégia de Open Source e InnerSource e tópicos de OSPO, além de arquitetura de soluções em nuvem. Ele também atua como palestrante e oferece treinamentos técnicos sobre os temas mencionados acima. Ele apresenta seu trabalho e pensamentos em conferências do setor, como o FOSDEM ou a InnerSource Commons Summit, e é ativo em comunidades open source há muito tempo. Com formação em ciência da computação e sociologia das organizações, ele possui uma perspectiva única sobre organizações de engenharia de software. Em funções anteriores, ele também trabalhou na introdução de Integração e Entrega Contínua em grandes instituições de pesquisa, em funções de DevOps para plataformas baseadas em nuvem de grande porte e desenvolveu software no domínio de telecomunicações.
```

2023-06-19 00:48 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> +Jacob Green, fundador da Mosslabs.io, é um artista de código aberto, estrategista e construtor de sistemas que
```suggestion
Jacob Green, fundador da Mosslabs.io, é um artista de open source, estrategista e construtor de sistemas que
```

2023-06-19 00:49 UTC, fer-correa commented on content/pt-br/about/board/_index.md
> + trabalha para expandir o impacto e a aplicação do código aberto na sociedade globalmente. Vindo de Baltimore, é apaixonado por código aberto em cidades e universidades, e trabalha para conectar inst
```suggestion
 trabalha para expandir o impacto e a aplicação de open source na sociedade globalmente. Vindo de Baltimore, é apaixonado por open source em cidades e universidades, e trabalha para conectar instituições por meio de open source. Antes da Mosslabs.io, Jacob foi diretor de iniciativas estratégicas na LTNGlobal, construindo uma rede global de transporte de vídeo única do zero e a partir de princípios fundamentais.
```

2023-06-19 00:53 UTC, fer-correa commented on content/pt-br/about/contact.md
> +subtitle: "Mantenha-se em contato - aqui estão todas as formas de entrar em contato com o InnerSource Commons"
```suggestion
subtitle: "Mantenha-se em contato - aqui estão todas as formas de entrar em contato com a InnerSource Commons"
```

2023-06-19 00:53 UTC, fer-correa commented on content/pt-br/about/contact.md
> +description: "Mantenha-se em contato com o InnerSource Commons."
```suggestion
description: "Mantenha-se em contato com a InnerSource Commons."
```

2023-06-19 00:54 UTC, fer-correa commented on content/pt-br/about/contact.md
> +        <p class="mb-4">A maioria das atividades da comunidade acontece em nosso <a href="https://join.slack.com/t/innersourcecommons/shared_invite/zt-1msf8vcqu-fYEHcyI1l4eSPq6rGprMXA">canal do Slack
```suggestion
        <p class="mb-4">A maioria das atividades da comunidade acontece em nosso <a href="https://join.slack.com/t/innersourcecommons/shared_invite/zt-1msf8vcqu-fYEHcyI1l4eSPq6rGprMXA">canal do Slack</a>. Você também pode se manter informado sobre as novidades, eventos e atividades da InnerSource Commons se inscrevendo em nossa lista de e-mails abaixo, nos seguindo no <a href="https://twitter.com/InnerSourceOrg">Twitter</a> e no <a href="https://www.linkedin.com/company/innersourcecommons">LinkedIn</a>, e se inscrevendo em nosso <a href="https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA">canal do YouTube</a>.</p>
```

2023-06-19 00:57 UTC, fer-correa commented on content/pt-br/about/members.md
> +O InnerSource Commons é uma corporação de associação, então os membros do ISC desempenham um papel semelhante aos acionistas de empresas de capital aberto.
```suggestion
A InnerSource Commons é uma corporação de membros associados, portanto, os membros do ISC desempenham um papel semelhante ao de acionistas em empresas de capital aberto.
```

2023-06-19 00:58 UTC, yuhattor commented
Thank you for the review and revision!
Please let me know when you need my support on this or when the PR is ready to merge!

2023-06-19 01:05 UTC, yuhattor reviewed
As sugestões agora são exibidas!

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/_index.md
> +        <p>Se você é novo no InnerSource ou quer saber mais sobre quem está implementando o InnerSource e por que e como começar, visite a seção de Aprendizado do site. Você encontrará uma variedade
```suggestion
        <p>Se você é novo no InnerSource ou deseja saber mais sobre quem está implementando InnerSource e o porquê e como começar, visite a seção de aprendizado do site. Você encontrará diversos recursos para ajudar a acelerar sua jornada ao InnerSource, incluindo materiais de treinamento, práticas recomendadas, livros, gravações de eventos anteriores e estudos de caso.
```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/_index.md
> +          <p>Apoiamos praticantes e aqueles que desejam aprender sobre o InnerSource por meio de uma ampla variedade de atividades. Para começar, junte-se à crescente comunidade ISC através do Slack
```suggestion
          <p>Apoiamos praticantes e aqueles que desejam aprender sobre InnerSource por meio de uma ampla variedade de atividades. Para começar, junte-se à crescente comunidade ISC através do Slack e se apresente. Você encontrará pessoas incríveis para lhe acompanhar em sua jornada InnerSource.</p>
```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/_index.md
> +        <p class="mb-4">A maior parte das ações na comunidade acontece em nosso <a href="https://join.slack.com/t/innersourcecommons/shared_invite/zt-1msf8vcqu-fYEHcyI1l4eSPq6rGprMXA">Canal do Slack<
```suggestion
            <p class="mb-4">A maior parte das ações na comunidade acontece em nosso <a href="https://join.slack.com/t/innersourcecommons/shared_invite/zt-1msf8vcqu-fYEHcyI1l4eSPq6rGprMXA">Canal do Slack</a>. Você também pode se manter informado sobre as novidades, eventos e atividades da InnerSource Commons assinando nossa lista de e-mails abaixo, nos seguindo no <a href="https://twitter.com/InnerSourceOrg">Twitter</a> e no <a href="https://www.linkedin.com/company/innersourcecommons">LinkedIn</a>, e se inscrevendo em nosso <a href="https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA">Canal do YouTube</a>.</p>
```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/about/_index.md
> +        <p>Nossa missão é estabelecer um corpo de conhecimento e educar indivíduos, organizações comerciais e sem fins lucrativos, centros de pesquisa e outras instituições sobre a adoção bem-sucedid
```suggestion
    <p>Nossa missão é estabelecer uma base de conhecimento e educar indivíduos, organizações com e sem fins lucrativos, centros de pesquisa e outras instituições sobre a adoção bem-sucedida das melhores práticas de InnerSource.</p>
```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/about/_index.md
> +        <p>Nós fornecemos um ambiente seguro para acumular e compartilhar conhecimento e experiências, encontrar melhores práticas, estabelecer padrões e ferramentas, produzir materiais educacionais
```suggestion
    <p>Oferecemos um ambiente seguro para acumular e compartilhar conhecimentos e experiências, encontrar as melhores práticas, criar padrões e ferramentas, produzir materiais educacionais e promover pesquisas para avançar na compreensão, adoção e prática de InnerSource.```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/about/_index.md
> +          <p>A InnerSource Commons utiliza métodos de código aberto para fornecer às organizações que praticam InnerSource um fórum para discutir e aprimorar a prática do InnerSource por meio do comp
```suggestion
          <p>A InnerSource Commons utiliza métodos de Open Source para fornecer às organizações que praticam o InnerSource um fórum para discutir e melhorar a prática do InnerSource por meio do compartilhamento de experiências (sob a Regra de Chatham House), criação e revisão dos padrões de InnerSource e a troca aberta de ideias.</p>
```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/about/_index.md
> +        <p>Indivíduos e empresas interessados são bem-vindos a participar e contribuir com conteúdo para o ISC. Em geral, o conteúdo contribuído será disponibilizado sob a <a href="https://creativeco
```suggestion
    <p>Indivíduos e empresas interessados ​​são bem-vindos a participar e contribuir com conteúdo para o ISC. Em geral, o conteúdo da contribuição será disponibilizado sob a licença <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International</a> atribuída a InnerSourceCommons.org. Nenhuma taxa é necessária para participar.</p> ```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/about/_index.md
> +        <p>A comunidade InnerSource Commons é aberta a todos. Alguns participantes da comunidade vão além e podem ser convidados a se tornar membros do ISC. A InnerSource Commons é uma corporação de
```suggestion
    <p>A comunidade InnerSource Commons é aberta a todas as pessoas. Alguns participantes da comunidade vão além, superando as expectativas, e podem ser convidados a se tornar membros do ISC. A InnerSource Commons é uma associação de membros, então os membros da ISC desempenham um papel semelhante aos acionistas de empresas de capital aberto.</p>```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/about/_index.md
> +        <p>Os membros têm direitos específicos no ISC; por exemplo, eles podem votar em eleições do conselho. Para ser elegível para a associação, a pessoa deve ser indicada por um membro atual. A as
```suggestion
        <p>Os membros têm direitos específicos na ISC; por exemplo, eles podem votar em eleições do conselho. Para ser elegível como um membro, a pessoa deve ser indicada por um membro atual. A associação é baseada exclusivamente no mérito, sem custo algum e restrita a indivíduos.
```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/about/_index.md
> +          <p>A InnerSource Commons é uma organização sem fins lucrativos 501(c)(3) governada por um conjunto de estatutos corporativos. O Conselho de Diretores estabelece as políticas e nomeia os ofi
```suggestion
      <p>A InnerSource Commons é uma organização sem fins lucrativos 501(c)(3) governada por um conjunto de estatutos corporativos. O Conselho de Administração define as políticas e nomeia os diretores responsáveis por estabelecer e executar essas políticas. O Conselho é eleito pelos membros da associação anualmente.</p>```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/about/board/_index.md
> +subtitle: A InnerSource Commons é uma organização sem fins lucrativos 501(c)(3) governada por um conjunto de estatutos sociais. O Conselho de Administração estabelece as políticas e nomeia os executi
```suggestion
subtitle: A InnerSource Commons é uma organização sem fins lucrativos 501(c)(3) regida por um conjunto de estatutos corporativos. O Conselho de Administração define a política e nomeia diretores que definem e executam a política. O Conselho é eleito pelos membros anualmente. A InnerSource Commons está incorporada nos Estados Unidos. À medida que a comunidade cresce, esperamos fundar organizações irmãs na União Europeia, América Latina e outras partes do mundo.```

2023-06-19 01:05 UTC, yuhattor commented on content/pt-br/about/board/_index.md
> +Isabel Drost-Fromm é Estrategista de Código Aberto na Europace AG, na Alemanha. Ela é membro da Apache Software Foundation, co-fundadora do Apache Mahout e orientou vários projetos em fase de incubaç
```suggestion
Isabel Drost-Fromm é Estrategista de Open Source na Europace AG, na Alemanha. Ela é membro da Apache Software Foundation, co-fundadora do Apache Mahout e orientou vários projetos em fase de incubação. Isabel se interessa por tudo relacionado a FOSS, busca e mineração de texto, com um bom conhecimento em aprendizado de máquina. Seguindo a natureza das pessoas que vivem em Berlim, ela adora receber amigos para uma breve visita. Como resultado, ela co-fundou e ainda é uma das mentes criativas por trás do Berlin Buzzwords, uma conferência de tecnologia sobre busca, escalabilidade e armazenamento.```

2023-06-19 01:06 UTC, yuhattor commented on content/pt-br/about/board/_index.md
> +Daniel Izquierdo Cortazar é pesquisador e um dos fundadores da Bitergia, uma empresa que oferece análises de software para ecossistemas de código aberto. Atualmente, é diretor de dados da Bitergia e
Faça a fusão uma vez! Acho que ficou bom!

2023-06-19 01:07 UTC, fer-correa commented on content/pt-br/about/privacy.md
> +Mantemos salvaguardas administrativas, técnicas e físicas projetadas para proteger a privacidade e a segurança das informações que mantemos sobre você. Quando você nos fornece informações pessoais, a
```suggestion
Mantemos salvaguardas administrativas, técnicas e físicas projetadas para proteger a privacidade e a segurança das informações que mantemos sobre você. Quando você nos fornece informações pessoais, a conexão entre seu computador e nosso servidor é criptografada usando software de Secure Sockets Layer (SSL) que criptografa essas informações. Usamos um Certificado Digital e páginas seguras serão identificadas por um ícone de cadeado e "https://" na barra de endereços. Armazenamos nossos dados em bancos de dados protegidos em servidores seguros com acesso restrito. Também utilizamos firewalls de hardware e software, fazemos verificação de vírus e malware e utilizamos serviços de monitoramento ao vivo 24 horas por dia, 7 dias por semana, para mitigar ameaças. No entanto, nenhum método de transmissão ou armazenamento é 100% seguro.
```

2023-06-19 01:11 UTC, fer-correa commented on content/pt-br/about/sponsors.md
> +              <li>Valor da marca ao demonstrar compromisso ativo com o InnerSource</li>
```suggestion
              <li>Valor da marca ao demonstrar compromisso ativo com a InnerSource</li>
```

2023-06-19 01:11 UTC, fer-correa commented on content/pt-br/about/sponsors.md
> +              <li>Valor da marca ao demonstrar compromisso ativo com o InnerSource</li>
```suggestion
              <li>Valor da marca ao demonstrar compromisso ativo com a InnerSource</li>
```

2023-06-19 01:12 UTC, fer-correa commented on content/pt-br/about/sponsors.md
> +              <li>Agradecimento em eventos e atividades do ISC</li>
```suggestion
              <li>Agradecimento em eventos e atividades da ISC</li>
```

2023-06-19 01:12 UTC, fer-correa commented on content/pt-br/about/sponsors.md
> +              <li>Palestrantes do InnerSource Commons fornecidos para seus eventos internos</li>
```suggestion
              <li>Palestrantes da InnerSource Commons fornecidos para seus eventos internos</li>
```

2023-06-19 01:12 UTC, fer-correa commented on content/pt-br/about/sponsors.md
> +              <li>Apoio do ISC para co-criação de conteúdo</li>
```suggestion
              <li>Apoio da ISC para co-criação de conteúdo</li>
```

2023-06-19 01:14 UTC, fer-correa requested changes
A new group of suggestions

2023-06-19 01:18 UTC, yuhattor commented
@fer-correa Thanks for the great work!
I merged everything once! What percentage of the work is done now?

2023-06-19 15:07 UTC, fer-correa commented
@yuhattor , almost done. We already reviewed about 75%.
Today we will finish all this content 😄

2023-06-19 15:11 UTC, yuhattor commented
WOW!!! That's amazing 😲 I can't wait to see the Brazilian-Portuguese ones in production!

2023-06-20 02:41 UTC, fer-correa commented on content/pt-br/community/_index.md
> +        <p class="section-title h2">Grupo de Trabalho de Roteiro de Aprendizado</p>
```suggestion
        <p class="section-title h2">Grupo de Trabalho do Caminho de Aprendizado</p>
```

2023-06-20 02:42 UTC, fer-correa commented on content/pt-br/community/_index.md
> +        <p>O Grupo de Trabalho de Roteiro de Aprendizado seleciona o <a href="/learn/learning-path/">Roteiro de Aprendizado InnerSource</a>, uma série de vídeos curtos e artigos que explicam e ensina
```suggestion
        <p>O Grupo de Trabalho do Caminho de Aprendizado seleciona o <a href="/learn/learning-path/">Caminho de Aprendizado InnerSource</a>, uma série de vídeos curtos e artigos que explicam e ensinam vários aspectos do InnerSource. O grupo de trabalho se reúne semanalmente. Para começar, junte-se ao canal #learning-path no Slack e se apresente.
```

2023-06-20 02:44 UTC, fer-correa commented on content/pt-br/community/_index.md
> +        <p>A InnerSource Commons Foundation é registrada como uma organização sem fins lucrativos 501(c)3 nos EUA, e fazer parte do Conselho é uma forma de a comunidade se comprometer mais profundame
```suggestion
        <p>A InnerSource Commons Foundation é registrada como uma organização sem fins lucrativos 501(c)3 nos EUA, e fazer parte do Conselho é uma forma da comunidade se comprometer mais profundamente com o InnerSource.
```

2023-06-20 02:46 UTC, fer-correa commented on content/pt-br/community/services.md
> +Nós fazemos o nosso melhor para garantir que as informações desta página sejam precisas e úteis o tempo todo. No entanto, qualquer link ou conteúdo listado abaixo não representa qualquer endosso ou r
```suggestion
Nós fazemos o nosso melhor para garantir que as informações desta página sejam precisas e úteis o tempo todo. No entanto, qualquer link ou conteúdo listado abaixo não representa qualquer endosso ou recomendação da InnerSource Commons e não significa que tenhamos qualquer associação com as organizações vinculadas.
```

2023-06-20 02:52 UTC, fer-correa commented on content/pt-br/learn/books/_index.md
> +Uma coleção de livros sobre InnerSource. Produzidos diretamente pelo InnerSource Commons ou em associação com ele.
```suggestion
Uma coleção de livros sobre InnerSource. Produzidos diretamente pela InnerSource Commons ou em associação com ela.
```

2023-06-20 02:55 UTC, fer-correa commented on content/pt-br/learn/books/adopting-innersource-principles-and-case-studies.md
> +Apesar de ter um diploma de bacharel em literatura francesa, **Danese Cooper** tem uma carreira de 30 anos na área de tecnologia, incluindo cargos de gerenciamento sênior de engenharia e estratégia d
```suggestion
Apesar de ter um diploma de bacharel em literatura francesa, **Danese Cooper** tem uma carreira de 30 anos na área de tecnologia, incluindo cargos de gerenciamento sênior de engenharia e estratégia de open source na Apple, Microsoft, Symantec, Sun, Intel e, mais recentemente, no PayPal. Ela é uma líder reconhecida no movimento de código aberto, por seu trabalho na Sun e como CTO da Wikimedia Foundation (casa da Wikipedia), e por seus
```

2023-06-20 02:58 UTC, fer-correa commented on content/pt-br/learn/books/adopting-innersource-principles-and-case-studies.md
> + muitos anos de serviço em Conselhos Diretores ou como consultora de projetos de código aberto conhecidos, incluindo a Open Source Initiative, Open Hardware Association, Mozilla, Drupal e Apache. Atu
```suggestion
 muitos anos de serviço em Conselhos Diretores ou como consultora de projetos open source conhecidos, incluindo a Open Source Initiative, Open Hardware Association, Mozilla, Drupal e Apache. Atualmente, ela atua como Presidente da Node.js Foundation. Danese fundou a InnerSourceCommons.org em 2015 como parte de um esforço de inicialização para o PayPal. Ela desenvolve e ministra treinamentos para organizações e indivíduos que trabalham com InnerSource por meio da DaneseWorks, sua consultoria. Ela palestra internacionalmente sobre tendências de Open Source e InnerSource, difundindo amplamente a ética Open Source.
```

2023-06-20 03:03 UTC, fer-correa commented on content/pt-br/learn/books/adopting-innersource-principles-and-case-studies.md
> +Como acadêmico, **Klaas-Jan Stol** realizou pesquisas sobre código aberto e InnerSource nos últimos 10 anos. Ele é professor na Escola de Ciência da Computação e Tecnologia da Informação do Universit
```suggestion
Como acadêmico, **Klaas-Jan Stol** realizou pesquisas sobre open source e InnerSource nos últimos 10 anos. Ele é professor na Escola de Ciência da Computação e Tecnologia da Informação do University College Cork, um pesquisador financiado pelo Lero - o Centro de Pesquisa de Software da Irlanda, e um Science Foundation Ireland Principal Investigator. O objetivo de sua pesquisa é entender melhor esses novos modos de trabalho de desenvolvimento e suas implicações para a indústria de software. Por exemplo, quando o open source estava surgindo como um tópico de pesquisa, a maioria das empresas não demonstrava muito interesse, principalmente devido a um mal-entendido sobre o que era o open source. Também não estava claro como as empresas poderiam se beneficiar do open source. Ao longo dos anos, isso mudou drasticamente devido a muitos estudos de pesquisa sobre esse tema, que são publicados em conferências acadêmicas, revistas e livros didáticos, que por sua vez são utilizados em cursos universitários. Algo semelhante está acontecendo agora com o InnerSource. Embora tenha sido um tópico de pesquisa por anos, ainda existem muitos equívocos sobre o que é o InnerSource e como as empresas podem se beneficiar ao adotá-lo. Klaas tenta preencher essa lacuna escrevendo livros como este.
```

2023-06-20 03:05 UTC, fer-correa commented on content/pt-br/learn/books/getting-started-with-innersource.md
> +Bem-vindo ao InnerSource, o poderoso movimento para desenvolvimento de software de código aberto dentro das paredes de uma única organização, onde a "abertura" de um projeto se estende entre equipes
```suggestion
Bem-vindo ao InnerSource, o poderoso movimento para desenvolvimento de software open source dentro das paredes de uma única organização, onde a "abertura" de um projeto se estende entre equipes dentro da empresa. Neste relatório, o editor e autor da O'Reilly, Andy Oram, leva você ao mundo do InnerSource, começando pela revisão dos princípios que tornam o desenvolvimento de open source bem-sucedido e, em seguida, descrevendo como o InnerSource tem funcionado no PayPal, o principal facilitador de comércio na Internet.
```

2023-06-20 03:07 UTC, fer-correa commented on content/pt-br/learn/books/getting-started-with-innersource.md
> +* Desenvolvimento com o GitHub: O GitHub mantém repositórios privados para projetos internos, bem como repositórios públicos para código de código aberto.
```suggestion
* Desenvolvimento com o GitHub: O GitHub mantém repositórios privados para projetos internos, bem como repositórios públicos para código open source.
```

2023-06-20 03:07 UTC, fer-correa commented on content/pt-br/learn/books/getting-started-with-innersource.md
> +**Andy Oram** é editor na O’Reilly Media. Funcionário da empresa desde 1992, Andy atualmente se especializa em tecnologias de código aberto e engenharia de software. Seus trabalhos para a O’Reilly in
```suggestion
**Andy Oram** é editor na O’Reilly Media. Funcionário da empresa desde 1992, Andy atualmente se especializa em tecnologias open source e engenharia de software. Seus trabalhos para a O’Reilly incluem os primeiros livros lançados por uma editora dos EUA sobre Linux, o título de 2001 Peer-to-Peer e o best-seller
```

2023-06-20 03:11 UTC, fer-correa commented on content/pt-br/learn/books/understanding-the-innersource-checklist.md
> +summary: A autora Silona Bonewald explica como a iniciativa InnerSource pode ajudar sua empresa a desenvolver software internamente, aplicando lições do movimento de código aberto. Uma lista de verif
```suggestion
summary: A autora Silona Bonewald explica como a iniciativa InnerSource pode ajudar sua empresa a desenvolver software internamente, aplicando lições do movimento open source. Uma lista de verificação guia você por várias etapas necessárias para produzir software utilizando a abordagem InnerSource, seja para toda a empresa ou apenas para uma equipe.
```

2023-06-20 03:12 UTC, fer-correa commented on content/pt-br/learn/books/understanding-the-innersource-checklist.md
> +Você deseja que seu trabalho diário seja mais parecido com o seu trabalho em um projeto de código aberto favorito? Suas equipes precisam reduzir a dívida técnica? Você deseja quebrar as barreiras ent
```suggestion
Você deseja que seu trabalho diário seja mais parecido com o seu trabalho em um projeto open source favorito? Suas equipes precisam reduzir a dívida técnica? Você deseja quebrar as barreiras entre as pessoas e permitir mais colaboração e reutilização?
```

2023-06-20 03:14 UTC, fer-correa commented on content/pt-br/learn/books/understanding-the-innersource-checklist.md
> +Venha aprender mais sobre uma lista de verificação InnerSource desenvolvida no PayPal. Ouça mais sobre nossos casos de sucesso com InnerSource e como estamos codificando nossas práticas para ajudar m
```suggestion
Venha aprender mais sobre um checklist InnerSource desenvolvida no PayPal. Ouça mais sobre nossos casos de sucesso com InnerSource e como estamos codificando nossas práticas para ajudar mais equipes no PayPal e além.
```

2023-06-20 03:14 UTC, fer-correa commented on content/pt-br/learn/books/understanding-the-innersource-checklist.md
> +A autora Silona Bonewald explica como a iniciativa InnerSource pode ajudar sua empresa a desenvolver software internamente, aplicando lições do movimento de código aberto. Uma lista de verificação gu
```suggestion
A autora Silona Bonewald explica como a iniciativa InnerSource pode ajudar sua empresa a desenvolver software internamente, aplicando lições do movimento open source. Um checklist guia você por várias etapas necessárias para produzir software utilizando a abordagem InnerSource, seja para toda a empresa ou apenas para uma equipe.
```

2023-06-20 03:15 UTC, fer-correa commented on content/pt-br/learn/books/understanding-the-innersource-checklist.md
> +* Maneiras de adaptar o InnerSource ao ambiente de negócios sem diluir os fundamentos do código aberto
```suggestion
* Maneiras de adaptar o InnerSource ao ambiente de negócios sem diluir os fundamentos do open source
```

2023-06-20 03:15 UTC, fer-correa commented on content/pt-br/learn/books/understanding-the-innersource-checklist.md
> +* O papel crucial do Committer Confiável no processo InnerSource
```suggestion
* O papel crucial do Trusted Committer no processo InnerSource
```

2023-06-20 03:16 UTC, fer-correa commented on content/pt-br/learn/books/understanding-the-innersource-checklist.md
> +* Adaptação da colaboração de código aberto para planejamento e gerenciamento
```suggestion
* Adaptação da colaboração open source para planejamento e gerenciamento
```

2023-06-20 03:17 UTC, fer-correa commented on content/pt-br/learn/books/understanding-the-innersource-checklist.md
> +**Silona Bonewald** é membro da comunidade de código aberto desde o final dos anos 90 e atualmente é diretora do InnerSource no Paypal.
```suggestion
**Silona Bonewald** é membro da comunidade open source desde o final dos anos 90 e atualmente é diretora do InnerSource no Paypal.
```

2023-06-20 03:18 UTC, fer-correa commented on content/pt-br/learn/patterns.md
> +        <p>O InnerSource Commons fornece um fórum para a comunidade compartilhar suas experiências e aprender uns com os outros na forma de Padrões InnerSource.
```suggestion
        <p>A InnerSource Commons fornece um fórum para a comunidade compartilhar suas experiências e aprender uns com os outros na forma de Padrões InnerSource.
```

2023-06-20 03:23 UTC, fer-correa requested changes
Well... @yuhattor , I really think we're done with this quest. 😃

2023-06-21 14:24 UTC, yuhattor commented
Now let's check it in the verification environment! Thanks for the amazing job!

2023-06-21 15:46 UTC, yuhattor commented
@fer-correa 

Here's a staging, please check that with your friends! 
I think there is some instability...
https://innersourcecommons.jp/pt-br/

2023-06-27 14:34 UTC, yuhattor commented
@fer-correa 
What is your overall impression?
Do you think it's ready to release? We need some other native speakers to check it out if you don't mind 👀

2023-06-27 15:32 UTC, fer-correa commented
Great idea @yuhattor 

The more reviewers we have the better it will be.
Otherwise, we will certainly get feedback from the community after publication, as I believe this will generate more engagement.

2023-07-04 15:40 UTC, galmeida125 commented
Hi everyone!

I did a brief review and the translation looks very good to me.

(native brazilian speaking here :))

2023-07-11 15:17 UTC, yuhattor commented
Thank you!!

Here's the current status
- [x] @fer-correa reviewed 
- [x] @galmeida125 reviewed

2023-07-11 15:18 UTC, yuhattor commented
Hi @rrrutledge, 

I think it's ready to merge after some confirmations about i18n settings.
Also I think we can finish the initial native check process here. What do you think? If you think it's mergeable in terms of the native check, please approve it!

2023-07-11 15:43 UTC, rrrutledge approved these changes
Thanks, @yuhattor ❗  Getting this in sounds great to me as it will allow us to finish our Brazilian Portuguese translation of the Learning Path.

2023-07-12 05:18 UTC, yuhattor commented
Fantastic! I'll start getting ready for the deployment 🚀

2023-08-03 11:33 UTC, yuhattor commented
NOW IT'S TIME TO MERGE 🎉 🎉 🎉 

Here's the staging site: https://isc-i18n.github.io/pt-br/
The staging site has the latest state of this branch, forked and merged with the current latest master. So this staging site will be the state after merging this PR.

Please review and confirm that it works properly
@rrrutledge: Could you please check that the website works correctlly, just in case
@fer-correa: Please double check that the language/contents are fine:)


@InnerSourceCommons/website-maintainers
I think I will be asking for an approve for the merge soon.What's going on now.
I will mention this to notify the current status.
jfyi: @voborgus and @andrea-kyurchiev

2023-08-03 12:17 UTC, rrrutledge commented
@marshmallowrobot is looking at how the Brazilian-translated learning path articles will show up on the website and can try those out with this version of the site to see if it works.

2023-08-04 00:57 UTC, yuhattor commented
Thank you! It looks like pt-br has not been merged into learning-path main/master yet.
I hope to be able to merge the following after merging this, but I wonder if Learning-Path Brazilian-Portuguese is ready to merge?? https://github.com/InnerSourceCommons/InnerSourceLearningPath/pulls

2023-08-04 01:04 UTC, fer-correa commented
We are working on these PRs as possible... I believe we are very close to crossing the finish line 😄

2023-08-04 01:46 UTC, yuhattor commented
@fer-correa Thanks!!

2023-08-04 12:31 UTC, rrrutledge commented
There are a few Learning Path PRs that [are already in](https://github.com/InnerSourceCommons/InnerSourceLearningPath/pulls?q=is%3Apr+is%3Aclosed).  You can go through the steps of [updating the website with new articles](https://github.com/InnerSourceCommons/InnerSourceLearningPath/tree/main/scripts#how-to-update-innersourcecommonsorg-with-new-articles) to see if those finished articles work with these changes.

2023-08-29 13:44 UTC, yuhattor commented
@InnerSourceCommons/website-maintainers 
@voborgus 
Please merge this
https://isc-i18n.github.io/pt-br/

2023-08-29 21:09 UTC, voborgus approved these changes
Confirm everything works as expected locally, going to merge and deploy this. 

@fer-correa @galmeida125 @yuhattor @rrrutledge you are rockstars! 🔥🔥🔥

2023-08-29 21:09 UTC, merged