Explain how to add InnerSource Stories in CONTRIBUTING.md
InnerSourceCommons/innersourcecommons.org pull request #686
Opened 2023-12-14 18:28 UTC by spier

2023-12-14 18:29 UTC, spier commented
@yuhattor I noticed that in your case in #683 you did not add the story of nifty to all translated versions of the site.
How did you determine to which translated versions to add the story to?

2023-12-15 01:27 UTC, jeffabailey requested changes

2023-12-15 01:27 UTC, jeffabailey commented on CONTRIBUTING.md
> +Here an [example PR](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/683) demonstrating this.
```suggestion
Here's an [example PR](https://github.com/InnerSourceCommons/innersourcecommons.org/pull/683) demonstrating this. 
```

2023-12-15 01:27 UTC, jeffabailey commented on CONTRIBUTING.md
>  * Follow the GitHub Guidelines on creating a pull request.
```suggestion
* Follow the [GitHub Pull Request Guidelines](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) to create a pull request.
```

2023-12-15 07:53 UTC, spier commented
@jeffabailey thanks for the review. I incorporated your changes. 👍

2023-12-15 16:46 UTC, rrrutledge approved these changes
Looks great ❗  Thank you!

2023-12-15 22:10 UTC, merged

2023-12-15 22:10 UTC, spier commented
@yuhattor I already merged this but if you want to add further details related to the translation pages for the InnerSource Stories, feel free to do so.

2023-12-18 10:57 UTC, yuhattor commented
I'm late to the party. But it's looking good!!
Thank you!

2023-12-18 10:58 UTC, yuhattor commented
For i18n, I think this line is all we need for now👍

> * For i18n contributors, we recommend reading [the instructions on how it works](i18n.md).