renames "Mailing List" to "Newsletter" across languages
InnerSourceCommons/innersourcecommons.org pull request #701
Opened 2024-01-29 20:39 UTC by andrea-kyurchiev

Translations are made with Google translate so might be useful to have a native speaker look over them before merge. 

Closes https://github.com/InnerSourceCommons/InnerSourceMarketing/issues/264

2024-02-12 18:40 UTC, rrrutledge commented
How did you do the translations?

2024-02-15 15:57 UTC, fer-correa requested changes
Hi all,
I added some small recommendations for adjustments to the text of the translation into Brazilian Portuguese.

2024-02-15 15:57 UTC, fer-correa commented on content/pt-br/_index.md
> +        <p class="h3 section-title">Junte-se ao nosso boletim informativo</p>
Cadastre-se em nossa newsletter

2024-02-15 15:57 UTC, fer-correa commented on content/pt-br/about/contact.md
> +        <p class="h3 section-title">Junte-se ao nosso boletim informativo</p>
Cadastre-se em nossa newsletter

2024-02-15 15:57 UTC, fer-correa commented on content/pt-br/about/privacy.md
> +- Se inscreve em nossa newsletter: A InnerSource Commons coleta informações de identificação pessoal (nome e endereço de e-mail) para enviar por e-mail notícias, eventos e artigos que achamos que voc
- Cadastre-se em nossa newsletter: A InnerSource Commons coleta informações de identificação pessoal (nome e endereço de e-mail) para enviar por e-mail notícias, eventos e artigos que achamos que você pode gostar.

2024-02-15 15:57 UTC, fer-correa commented on content/pt-br/community/_index.md
> +        <p class="h3 section-title">Junte-se ao nosso boletim informativo</p>
Cadastre-se em nossa newsletter

2024-02-19 03:33 UTC, yuhattor commented on content/ja/community/_index.md
> +        <p class="h3 section-title">ニュースレターに参加する</p>
```suggestion
        <p class="h3 section-title">ニュースレターを定期購読する</p>
```

2024-02-19 03:33 UTC, yuhattor commented on content/ja/about/_index.md
> +        <p class="h3 section-title">ニュースレターに参加する</p>
```suggestion
        <p class="h3 section-title">ニュースレターを定期購読する</p>
```

2024-02-19 03:33 UTC, yuhattor commented on content/ja/_index.md
> +        <p class="h3 section-title">ニュースレターに参加する</p>
```suggestion
        <p class="h3 section-title">ニュースレターを定期購読する</p>
```

2024-02-19 03:35 UTC, yuhattor commented
🇯🇵 Done 🙌

2024-02-20 18:46 UTC, rrrutledge commented
Thanks for all of these reviews!  @andrea-kyurchiev is out this week but should be able to take a look next week.

2024-04-11 13:18 UTC, CiaraFlanagan approved these changes

2024-04-11 13:18 UTC, merged

2024-04-11 13:20 UTC, CiaraFlanagan commented
Hi @rrrutledge, @andrea-kyurchiev

I've merged the proposed change from 'mailing list' to 'newsletter'. Will keep my eye on this to see if it looks ok on deployment.