updating sponsor information and numbers
InnerSourceCommons/innersourcecommons.org pull request #752
Opened 2024-04-26 10:36 UTC by OliveCannon

updating sponsor information and numbers

2024-04-29 08:18 UTC, andrea-kyurchiev approved these changes

2024-04-29 08:23 UTC, andrea-kyurchiev requested changes, later dismissed
The numbers will need updated for the translations as well: 
![image](https://github.com/InnerSourceCommons/innersourcecommons.org/assets/77273562/bbc6ed0d-5649-4577-ac01-c0148e3dabbc)

2025-01-29 17:05 UTC, CiaraFlanagan approved these changes

2025-01-29 17:08 UTC, CiaraFlanagan approved these changes

2025-01-29 17:09 UTC, CiaraFlanagan approved these changes

2025-02-05 16:07 UTC, merged